print("VOCÊ ESTÁ PARTICIPANDO DA NOSSA PROMO TREINA JUNTO")

frequência = float(input("Digite o número de frequência: "))


if frequência == 21:
    print("UHUU! AGORA VOCÊ PODE PRESENTEAR UM AMIGO OU AMIGA PARA TREINAR COM VOCÊ!")

else:
    print("QUE BOM VER VOCÊ DE VOLTA! A PARTIR DE AGORA INICIAMOS MAIS UMA CONTAGEM DE 21 DIAS PARA A PROMO TREINA JUNTO")







